# light weight node image
FROM node:20-alpine

# set working directory inside the container

WORKDIR /app

# Copy only package.json/package-lock first

COPY package*.json ./

# install all dependencies
RUN npm install

# copy the rest of the app 
COPY . .


