# light weight node image
FROM node:20-alpine

# set working directory inside the container

WORKDIR /app

# Copy only package.json/package-lock first

COPY package*.json ./

# install all dependencies
RUN npm install

# copy the rest of the app 
COPY . .

# allow the dev server to listen on all interfaces
ENV HOST=0.0.0.0

# Helps file watching work better inside Docker on some systems
ENV CHOKIDAR_USEPOLLING=true

# expose the dev server port   
EXPOSE 3000

# start the dev server
CMD [ "npm","start" ]





